/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Heraizen.Server.MongoDB;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
